#!/usr/bin/env bash
# Regenerate the Homebrew formula for a release and push it to the tap.
#
#   scripts/update-homebrew.sh v0.1.1-alpha [path-to-tap-checkout]
#
# Needs `gh` logged in with push access to its-banana-coder/homebrew-noida.
set -euo pipefail

tag="${1:?usage: update-homebrew.sh <tag> [tap-dir]}"
version="${tag#v}"
repo="its-banana-coder/noida"
tap_repo="its-banana-coder/homebrew-noida"
tap="${2:-$(mktemp -d)/homebrew-noida}"

work="$(mktemp -d)"
gh release download "$tag" -R "$repo" -p '*.sha256' -D "$work"
sha() { cut -d' ' -f1 "$work/noida-$1.tar.gz.sha256"; }

[ -d "$tap/.git" ] || gh repo clone "$tap_repo" "$tap"
mkdir -p "$tap/Formula"
cat > "$tap/Formula/noida.rb" <<RUBY
# Generated by scripts/update-homebrew.sh; do not edit by hand.
class Noida < Formula
  desc "Terminal IDE built around Claude Code and Codex"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/noida-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/noida-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/noida-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "noida"
  end

  test do
    assert_match "noida", shell_output("#{bin}/noida --version")
  end
end
RUBY

git -C "$tap" add Formula/noida.rb
git -C "$tap" commit -q -m "noida $version" || { echo "formula already up to date"; exit 0; }
git -C "$tap" push -q
echo "pushed formula for $tag to $tap_repo"
